### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by ysk24ok**
I've decided to use GitHub Actions instead of Travis CI because

- [Travis CI set credit allotment for public repositories](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only)
- we have to serve our wheels outside of PyPI to deal with #35 

When new release is published, the Actions workflow uploads wheels to the release page.
Originally in https://github.com/espnet/warp-ctc/issues/35#issuecomment-745237924 , I was going to serve wheels in this repository, but I found that serving wheels as assets of a release page is much easier.

Users will be able to  install a wheel like this,

```console
$ pip install warpctc_pytorch==X.Y.Z+torchXX.cudaXX -f https://github.com/espnet/warp-ctc/releases/tag/vX.Y.Z
```

After this pull request is merged, I'll publish a new release and see if the wheels are attached to the release page.

### CODE REVIEW

**Comment by ysk24ok** [comment]
Hm, I'm not sure why the Actions workflow doesn't work in this pull request ..

**Comment by ysk24ok** [comment]
@sw005320 Could you review this PR?

**Review by sw005320 — APPROVED** [review]
LGTM!
This is a very clear strategy for me.

**Comment by ysk24ok** [comment]
Thank you for the review. Let me merge this PR.

**Pull request merged**
